version: '2.3'
services:
  website:
    container_name: apache
    image: 'php:apache'
    ports:
    - "8080:80"
    
    volumes:
        - C:\Users\elitbook\Desktop\student-list-master\website:/var/www/html
    networks:
        - app_net
networks:
  app_net:
        name: "work_network"
        driver: bridge
        
        
    api:
        image:'api1'
        volumes:
            - C:\Users\elitbook\Desktop\devops project\student-list-master\simple_api
        ports:
            - "5000:5000"
networks:
        - app_net
networks:
  app_net:
        name: "work_network"
        driver: bridge
